### ISSUE TITLE
wifi 201 conn issue (AP not found)

### ISSUE THREAD

**Issue by morbos** [mruby-esp32/mruby-esp32#2]
resolved by clearing the datastructure first. (also include <string.h> at the top)

        wifi_config_t wifi_config;
        memset((void *)&wifi_config, 0, sizeof(wifi_config_t));
  snprintf(wifi_config.sta.ssid, sizeof(wifi_config.sta.ssid), "%s", ssid);
  snprintf(wifi_config.sta.password, sizeof(wifi_config.sta.password), "%s", pa\
ssword);

**Comment by carsonmcdonald** [comment]
Took a while to get back to this but I've pulled it into the code.
