### ISSUE TITLE
ESP-IDF v4.4 support

### ISSUE THREAD

**Issue by fliiiix** [mruby-esp32/mruby-esp32#25]
```
make[1]: *** No rule to make target 'true'.  Stop.
make: *** [/home/l33tname/esp/esp-idf/make/project.mk:649: component-mruby_component-build] Error 2
``` 

Does not work with the latest ESP-IDF v4.4.
I think or im holding it wrong. But i don't really understand the error here with true which should be a target.

Tested with v4.2.3 which worked fine.

**Comment by pandax381** [comment]
Thank you for your report.
I will check it later.

**Comment by pandax381** [comment]
@fliiiix
As you reported, I have reproduced the build issue and fixed it.
Please confirm that the build should now pass.
